#
# Makefile for the touchscreen drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_TOUCHSCREEN_SEC_TS)	+= sec_ts/
obj-$(CONFIG_TOUCHSCREEN_SEC_TS_Y771)	+= sec_ts/y771/
obj-$(CONFIG_TOUCHSCREEN_FTS)		+= stm/
obj-$(CONFIG_TOUCHSCREEN_SEC_TS_Y661_DUAL)	+= sec_ts_y661_dual/
obj-$(CONFIG_TOUCHSCREEN_CYPRESS_CYTTSP5)	+= cyttsp5/
